spring.application.name=farmaflow-agent
server.port=3333
agent.version=0.0.1-SNAPSHOT
agent.internet-check.url=https://www.google.com/generate_204
agent.internet-check.timeout-ms=3000
agent.tray.icon-path=
agent.update.manifest-url=
